### ISSUE TITLE
How to work with lerna?

### ISSUE THREAD

**Issue by Zaynex** [tableau/npm-pack-here#12]
## Question

Hi, I am suffering from local node Dependencies debugging.I have some question.

The context of the question is based on [this article](https://engineering.tableau.com/reliable-development-workflows-for-local-node-dependencies-aka-why-we-wrote-npm-pack-here-ddeea7eb43ad)

If `widget` package have a dependence  like `@babylonjs/core`,
```
widgets
  node_modules
    @types
      react
    react
    @babylonjs/core
```
if we just run `npm pack`,it doesnt include `@babylonjs/core`(in node_modules),just import it in dist/files
```
import { Engine, Scene, Color4, MeshBuilder, Vector3} from '@babylonjs/core';
```
at the same time, `edit-axis-dialog` doesn't have @babylonjs/core in node_modules.

If we run, edit-axis-dialog should show error message like`Can't resolve '@babylonjs/core' in ....` .

There is two way can solve.
1. add `@babylonjs/core` in devDependency to `edit-axis-dialog`,then install.
2. copy `widget's node_modules` to `edit-axis-dialog node_modules`.

Does `npm-pack-here` consider this ?
In lerna,if using hosit, the  `@babylonjs/core` maybe doesn't in widget's node_modules, but in its parent directory's node_modules.

## Additional Context

- Node/npm version: [Node v14.15.2/npm 6.14.9]
- OS: [OSX 10.15]

https://github.com/wclr/yalc/issues/95#issuecomment-768800891

**Comment by greyepoxy** [comment]
Hi @Zaynex,
Not sure I totally follow you, so checking my understanding you have a lerna project setup like the following.
```
your-lerna-workspace/
  package.json
  packages/
    widgets/
      package.json (dependencies includes react and @bablonjs/core)
    edit-axis-dialog/
      package.json (dependencies includes widgets)
```
Is this correct? Could you be more specific about the problem you are running into with this setup?

I am not aware of anyone using `npm-pack-here` with lerna so not sure it will work for your situation, will need more specifics to be able to determine that.


Looking at your post to yalc, if the question is about if `npm-pack-here` supports locally testing mult-level transitive dependencies, then the answer is yes. To make it work you need to use the [`useGlobalCache`](https://github.com/tableau/npm-pack-here#useglobalcache-optional) option although be aware that there are some unsolved issues with it https://github.com/tableau/npm-pack-here/issues/10

**Comment by Zaynex** [comment]
@greyepoxy  Thanks, useGlobalCache is helpful.
